
version: 2

jobs:
  build:
    macos:
      xcode: "10.0.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      LANG: en_US.UTF-8
    steps:
      ## Pre-start iOS Simulator
      # The `|| true` is necessary because xcrun will complain about incorrect usage.
      # It says that `-t <instruments-template-name>` should be provided. If we provided
      # that, it would take longer, work less reliable and create a bunch of trace files
      # that we'd have to remove again so the project folder is empty on checkout.
      # If we don't pass `-t`, the Simulator starts anyway...
      - run:
          name: Pre-start iOS Simulator
          command: xcrun instruments -w "iPad Air 2 (11.3)" || true
      
      ## Create output directories
      - run:
          name: Create output directories
          command: |
            mkdir "/Users/distiller/output"
            mkdir "/Users/distiller/output/xcodebuild-logs"

      ## Checkout source
      - checkout
      
      ## Check ruby version and GEM_HOME
      - run: 
          name: Check ruby and GEM_HOME 
          command: |
            which ruby
            echo ${GEM_HOME}

      ## Install bundle (cache-wrapped)
      - restore_cache:
          keys:
            - v5-bundle-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v5-bundle-cache-{{ .Branch }}
            - v5-bundle-cache
      - run: bundle install
      - save_cache:
          key: v5-bundle-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            # This is basically GEM_HOME, hardcoded.
            # It MUST be updated if the ruby version changes!
            # Due to CircleCIs complete stupidity, there doesn't seem to be any
            # decent way of setting the path by, say, using $GEM_HOME, for example,
            # because these morons still haven't made it possible to interpolate
            # env vars throughout the config file. They even RECOMMEND hardcoding here:
            # https://discuss.circleci.com/t/can-i-use-variables-in-cache-paths/11393/3
            - /Users/distiller/.gem/ruby/2.5.1

      ## Install pods (cache-wrapped)
      - restore_cache:
          keys:
            - v4-pod-cache-{{ .Branch }}-{{ checksum "Podfile.lock" }}
            - v4-pod-cache-{{ .Branch }}
            - v4-pod-cache
      - run: bundle exec pod install
      - save_cache:
          key: v4-pod-cache-{{ .Branch }}-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods

      ## Run tests
      - run:
          name: Run tests
          command: xcodebuild -workspace TastyTomato.xcworkspace -scheme "TastyTomato" -destination 'platform=iOS Simulator,name=iPad Air 2,OS=11.3' clean build test | tee "/Users/distiller/output/xcodebuild-logs/xcodebuild-verbose.log" | xcpretty | tee "/Users/distiller/output/xcodebuild-logs/xcodebuild-xcpretty.log"
      
      ## Store artifacts
      - store_artifacts:
          path: "/Users/distiller/output"
